-- Generated by _tools/generate_block_state_schemas.py. Do not edit.
MC=MC or {}
MC.GeneratedBlockStateSchemaCatalog={domains={},rows={}}
MC.GeneratedStateMetadata={
	minecraftId="26.2-pre-4",
	worldVersion=4897,
	seriesId="main",
	generatorVersion=2,
	schemaCatalogVersion=2,
	propertyDomainCount=51,
	schemaHash="f5e75267ed182adb4e65c936e8473c2f22ac1c72ca0642e93752fa9d6bd87e7d",
	reportSha256="dec22eb9547b0bbea396cbf35569f7ec81b7be662775ce03dc2236227473af7b",
	blockCount=1196,
	stateCount=32366,
}
local parts={
	"mc/generated/sh_generated_block_state_schemas_part001.lua",
	"mc/generated/sh_generated_block_state_schemas_part002.lua",
}
if SERVER then for _,path in ipairs(parts) do AddCSLuaFile(path) end end
for _,path in ipairs(parts) do include(path) end
